# Generated by Django 3.2.25 on 2025-06-10 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_equipos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipos',
            name='record_de_partidos',
            field=models.IntegerField(),
        ),
    ]
