# Generated by Django 3.2.25 on 2025-06-10 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_equipos_record_de_partidos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipos',
            old_name='record_de_partidos',
            new_name='partidos_ganados_en_la_temporada',
        ),
    ]
