# Generated by Django 3.2.25 on 2025-06-17 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_rename_record_de_partidos_equipos_partidos_ganados_en_la_temporada'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipos',
            name='partidos_perdidos_en_la_temporada',
            field=models.IntegerField(default=0),
        ),
    ]
